version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    depends_on:
      - product-service
      - user-service
      - order-service

  product-service:
    build:
      context: ./product-services
      dockerfile: Dockerfile
    ports:
      - "6002:6002"
    environment:
      - MONGO_URI=mongodb+srv://priyadasunkc21:I9C1ryXvwKDaYRp6@users.c9fon.mongodb.net/?retryWrites=true&w=majority&appName=user
      - CLOUDINARY_CLOUD_NAME=dgbjkmftz
      - CLOUDINARY_API_KEY=857485585361998
      - CLOUDINARY_API_SECRET=Tx-irm58gxZURFhlHJdhHYUBry8

  user-service:
    build:
      context: ./user-services
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://priyadasunkc21:I9C1ryXvwKDaYRp6@users.c9fon.mongodb.net/?retryWrites=true&w=majority&appName=user
      - JWT_SECRET=kdm@#83jaKMDn22#3nvaCMq@!&mnskd832mvnaksd#

  order-service:
    build:
      context: ./order-services
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb+srv://udayanga:udayanga@udayanga.yebyk.mongodb.net/oder
      - JWT_SECRET=kdm@#83jaKMDn22#3nvaCMq@!&mnskd832mvnaksd#
